version: '3' 

services: 
  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports: 
      - 5000:5000
    expose:
      - 5000
    volumes:
      - model:/src/model
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000
    expose:
      - 3000
  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model

volumes:
  imgs:
  data:
  model: