version: '3' 

services: 
    redis:
      image: redis
      ports:
        - 6379:6379
      expose:
        - 6379
      restart: unless-stopped
    front:  
      image: front
      ports: 
        - 5000:5000
    back:  
      image: back
      ports: 
        - 8000:8000
      environment:
        - REDIS=redis
      depends_on:
        - redis