version: '3' 

services: 
    redis:
      image: redis
      ports:
        - 6379:6379
      expose:
        - 6379
      restart: unless-stopped
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=12345678
      expose:
        - 8080
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: unless-stopped
    front:  
      image: front
      ports: 
        - 5000:5000
    back:  
      image: back
      ports: 
        - 8000:8000
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=12345678
        - DB_NAME=postgres
        - DB_HOST=postgres
      depends_on:
        - redis
        - postgres
volumes: 
    pgdata: