version: '3' 

services: 
    redis:
      image: redis
      ports:
        - 6379:6379
      expose:
        - 6379
      restart: unless-stopped
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=12345678
      expose:
        - 8080
      restart: unless-stopped
    front:  
      image: front
      ports: 
        - 5000:5000
      expose:
        - 5000
    back:  
      image: back
      ports: 
        - 8000:8000
      expose:
        - 8000
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=12345678
        - DB_NAME=postgres
        - DB_HOST=postgres
      depends_on:
        - redis
        - postgres
    nginx:
      image: nginx
      ports:
        - 80:80
        - 443:443
      expose:
        - 80
        - 443
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - front
        - back